use_frameworks!

platform :ios, '10.0'

target 'Go23KeychainSwift_Example' do
  pod 'Go23KeychainSwift', :path => '../'

  target 'Go23KeychainSwift_Tests' do
    inherit! :search_paths

    
  end
end
